### ISSUE TITLE
The original videos of omniscenes

### ISSUE THREAD

**Issue by liubonan123** [82magnolia/panoramic-localization#1]
Hi! Thank you for the great work. I noticed that the Omniscenes dataset only provides some images extracted from video sequences. I was wondering if it's possible to access the original video files.
Thank you in advance for your help!

**Comment by 82magnolia** [comment]
Hi, sorry for the late reply. Unfortunately, we cannot provide the raw video files used for creating Omniscenes. However, I can provide the full set of images (including those not having pose annotations) subsampled from the 360 video captured for making Omniscenes. If this is okay with you, please send me an email (oottramsmi@gmail.com) and I provide the links to the data.
